spring.application.name=insight-flow-server
server.port=8080
cors.allowed-origins=http://localhost:4200
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
gemini.api-key={$ your-gemini-key}
# spring.data.mongodb.uri=mongodb+srv://Ubaida:GCu-2021@cluster0.kj42s.mongodb.net/InsightFlow
spring.data.mongodb.uri=mongodb+srv://Ubaida:GCu-2021@cluster0.kj42s.mongodb.net/InsightFlow
spring.data.mongodb.auto-index-creation=true
management.health.mongo.enabled=false
