spring.application.name=insight-flow-server
server.port=8080
cors.allowed-origins=http://localhost:4200
gemini.api-key=${GEMINI_API_KEY}
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.data.mongodb.uri=mongodb+srv://Ubaida:GCu-2021@cluster0.kj42s.mongodb.net/InsightFlow
logging.level.org.springframework.data.mongodb=DEBUG
management.health.mongo.enabled=false
management.health.defaults.enabled=false
