package com.example.insightflowserver.constants;

public class MedicalDisclaimer {
    public static final String MEDICAL_DISCLAIMER = """
                ⚠️ MEDICAL DISCLAIMER: This report is generated by an AI system for \
                informational purposes only. It is NOT a substitute for professional \
                medical advice, diagnosis, or treatment. Always consult a qualified \
                healthcare provider before making any medical decisions. If you are \
                experiencing a medical emergency, call your local emergency number immediately.
            """;
}
